#!/usr/bin/env bash
set -euo pipefail

HERE="$(dirname "$(readlink -f "${0}")")"

export APPDIR="${APPDIR:-$HERE}"
export SMU_APPDIR="${SMU_APPDIR:-$HERE}"
export LD_LIBRARY_PATH="${HERE}/usr/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

NETHELPER_TMP="/tmp/nethelper-${USER}-${RANDOM}"

cp "${HERE}/usr/bin/nethelper" "$NETHELPER_TMP"
chmod +x "$NETHELPER_TMP"

(
  setsid pkexec "$NETHELPER_TMP" "$@" >/dev/null 2>&1 &
)
while [ ! -S /tmp/nethelper.sock ]; do sleep 0.05; done
exec "${HERE}/usr/bin/suspend" "$@"
